# Generated by Django 5.2.3 on 2025-06-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyitem',
            name='product_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='warrantyitem',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='warrantyitem',
            name='store_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='warrantyitem',
            name='warranty_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
