# Generated by Django 5.2.3 on 2025-06-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_warrantyitem_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyitem',
            name='product_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warrantyitem',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
    ]
